#include "read_input.cpp"
#include "wing_geometry.cpp"
#include "write_output.cpp"
#include "induced_velocity.cpp"
#include "gauss.cpp"
#include "wake_geometry.cpp"
#include "equ_system.cpp"
#include "lift_force.cpp"
#include "drag_force.cpp"
#include "PitchMoment.cpp"
#include "longtrim.cpp"

